// import Blog from '@/components/Blog'
import React from 'react'

export const metadata = {
    title: "All Blog",
    description: "Generated by create next app"
}

const Blogs = () => {
  return (
    <div>
      Hello world!!
    </div>
  )
}

export default Blogs
